// ==========================================
// HYBRID BRAIN CONSTANTS (constants_brain.js)
// Pure definitions for the engine layers.
// ==========================================

export const DOMAINS = {
  SYSTEMIC: 'SYSTEMIC',
  AEROBIC: 'AEROBIC',
  LOCAL_PUSH: 'LOCAL_PUSH',
  LOCAL_PULL: 'LOCAL_PULL',
  LOCAL_LEGS: 'LOCAL_LEGS',
  COMPLIANCE: 'COMPLIANCE',
  STRENGTH: 'STRENGTH'
};

export const PATTERNS = {
  STAGNATION_STRENGTH: 'STAGNATION_STRENGTH',
  MOMENTUM_STRENGTH: 'MOMENTUM_STRENGTH',
  SYSTEMIC_OVERREACHING: 'SYSTEMIC_OVERREACHING',
  LOCAL_FATIGUE_PUSH: 'LOCAL_FATIGUE_PUSH',
  LOCAL_FATIGUE_PULL: 'LOCAL_FATIGUE_PULL',
  LOCAL_FATIGUE_LEGS: 'LOCAL_FATIGUE_LEGS',
  AEROBIC_FATIGUE: 'AEROBIC_FATIGUE',
  AEROBIC_DETRAINING: 'AEROBIC_DETRAINING',
  EXCELLENT_COMPLIANCE: 'EXCELLENT_COMPLIANCE',
  POOR_COMPLIANCE: 'POOR_COMPLIANCE'
};

export const ACTIONS = {
  REDUCE_VOLUME: 'REDUCE_VOLUME',
  INCREASE_VOLUME: 'INCREASE_VOLUME',
  MAINTAIN: 'MAINTAIN',
  ADD_RECOVERY_DAY: 'ADD_RECOVERY_DAY',
  CONVERT_TO_EASY_RUN: 'CONVERT_TO_EASY_RUN',
  REDUCE_INTENSITY: 'REDUCE_INTENSITY'
};

export const THRESHOLDS = {
  HIGH_RPE: 8.5,
  FATIGUE_CRITICAL_ACWR: 1.5,
  FATIGUE_DANGER_ACWR: 1.3,
  LOCAL_SETS_HIGH_72H: 15,
  STAGNATION_WEEKS: 3,
  E1RM_VARIANCE_TOLERANCE: 0.025, // 2.5%
  COMPLIANCE_POOR: 0.60,
  COMPLIANCE_GOOD: 0.85
};

export const PRIORITY_WEIGHTS = {
  INJURY_PREVENTION: 100, // Highest
  RECOVERY: 80,
  AEROBIC_MAINTENANCE: 60,
  MAX_STRENGTH: 40,
  HYPERTROPHY: 20       // Lowest
};
